name: Build and Publish Docker Image

on:
  push:
    branches:
      - '**'                
    tags-ignore:
      - '**'                
    paths-ignore:
      - '.github/workflows/**' 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      IMAGE_NAME: docker-pipeline-demo
      REPO_OWNER: ${{ github.repository_owner }}
      BRANCH_NAME: ${{ github.ref_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Normalize repo/branch names to lowercase
        id: vars
        run: |
          echo "repo=$(echo $REPO_OWNER | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
          echo "branch=$(echo $BRANCH_NAME | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image for branch
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.vars.outputs.repo }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.branch }}
          platforms: linux/amd64

      - name: Tag and push latest (only on main)
        if: github.ref == 'refs/heads/main'
        run: |
          docker pull ghcr.io/${{ steps.vars.outputs.repo }}/${{ env.IMAGE_NAME }}:main
          docker tag ghcr.io/${{ steps.vars.outputs.repo }}/${{ env.IMAGE_NAME }}:main ghcr.io/${{ steps.vars.outputs.repo }}/${{ env.IMAGE_NAME }}:latest
          docker push ghcr.io/${{ steps.vars.outputs.repo }}/${{ env.IMAGE_NAME }}:latest
